const keys = ["calibrate", "findingBase", "baseAutoLocked", "baseManualLocked", "sampleHint", "sampleHintBw", "sampleHintShort", "sampleReady", "cancelCalibration", "useSample", "sampleError_noBase", "sampleError_clipped", "sampleError_textured", "sampleError_unstable", "cameraColorLocked", "cameraColorAuto", "findBaseAgain", "detectedBase"];
const translations = {
  en: ["Calibrate", "Finding film base · hold still…", "Film base estimated · held", "Sampled film base · held", "Original negative: drag over a clear orange film edge. Avoid holes and images.", "Original negative: select a clear, unexposed film edge.", "Tap or drag on the clear film edge.", "Uniform sample ready. Confirm to apply.", "Cancel", "Use this sample", "No reliable film base found. Show a clear film edge or sample it manually.", "This area is too bright. Avoid holes and lower the camera exposure or backlight.", "This area contains detail. Choose a clean, uniform film edge.", "The image is changing. Hold still and try again.", "Camera exposure and white balance locked", "Camera color is still automatic; recalibrate if it changes.", "Find film base again", "Detected film base"],
  zh: ["校准", "正在寻找片基，请保持稳定…", "片基已自动估计并固定", "手动片基已固定", "当前显示原始负片：拖动选择无影像的橙色片边，避开齿孔。", "当前显示原始负片：选择未曝光、没有影像的透明片边。", "点选或拖动到干净的片边。", "取样区域均匀，可以确认应用。", "取消", "使用此片基", "未找到可靠片基，请露出干净片边，或手动取样。", "此处过亮，请避开齿孔，降低相机曝光或灯板亮度。", "此处包含影像或纹理，请选择均匀、干净的片边。", "画面尚未稳定，请保持不动后重试。", "相机曝光与白平衡已锁定", "相机仍在自动调色；颜色变化时请重新校准。", "重新自动寻找片基", "检测到的片基"],
  ja: ["校正", "片基を検出中・動かさずにお待ちください…", "片基を自動推定・固定済み", "手動で採取した片基を固定済み", "元のネガを表示中：画像のないオレンジ色の縁を選択。穴を避けてください。", "元のネガを表示中：未露光で画像のない透明な縁を選択してください。", "きれいな縁をタップ、またはドラッグしてください。", "均一な領域です。確定すると適用します。", "キャンセル", "この片基を使用", "片基を検出できません。きれいな縁を入れるか手動で選択してください。", "明るすぎます。穴を避け、カメラの露出または光源の明るさを下げてください。", "模様があります。均一できれいな縁を選択してください。", "画面が安定していません。動かさずに再試行してください。", "カメラの露出とホワイトバランスを固定済み", "カメラは自動調整中です。色が変わったら再校正してください。", "片基を再検出", "検出した片基"],
  ru: ["Калибровка", "Ищем основу плёнки · не двигайте…", "Основа оценена и зафиксирована", "Образец основы зафиксирован", "Исходный негатив: выберите чистый оранжевый край без изображения и перфорации.", "Исходный негатив: выберите прозрачный неэкспонированный край.", "Коснитесь чистого края или перетащите точку.", "Образец однородный. Подтвердите применение.", "Отмена", "Применить образец", "Основа не найдена. Покажите чистый край или выберите его вручную.", "Слишком ярко. Избегайте отверстий, уменьшите экспозицию камеры или подсветку.", "Здесь есть детали. Выберите чистый однородный край.", "Изображение меняется. Не двигайте и повторите.", "Экспозиция и баланс белого заблокированы", "Цвет камеры автоматический; при изменении повторите калибровку.", "Найти основу снова", "Найденная основа"],
  es: ["Calibrar", "Buscando la base · mantén inmóvil…", "Base estimada y fijada", "Muestra de base fijada", "Negativo original: selecciona un borde naranja limpio, sin imagen ni perforaciones.", "Negativo original: selecciona un borde transparente sin exponer.", "Toca o arrastra sobre el borde limpio.", "Muestra uniforme. Confirma para aplicar.", "Cancelar", "Usar muestra", "No se detectó una base fiable. Muestra un borde limpio o selecciónalo a mano.", "Zona demasiado clara. Evita las perforaciones y reduce la exposición o la luz.", "Esta zona contiene detalles. Elige un borde limpio y uniforme.", "La imagen cambia. Mantén inmóvil y vuelve a intentar.", "Exposición y balance de blancos bloqueados", "El color de la cámara sigue en automático; recalibra si cambia.", "Buscar la base de nuevo", "Base detectada"],
  fr: ["Calibrer", "Recherche du support · restez immobile…", "Support estimé et fixé", "Échantillon du support fixé", "Négatif original : sélectionnez un bord orange propre, sans image ni perforations.", "Négatif original : sélectionnez un bord transparent non exposé.", "Touchez ou faites glisser sur le bord propre.", "Échantillon uniforme. Confirmez pour appliquer.", "Annuler", "Utiliser l’échantillon", "Support introuvable. Montrez un bord propre ou sélectionnez-le manuellement.", "Zone trop claire. Évitez les trous, réduisez l’exposition ou le rétroéclairage.", "Cette zone contient des détails. Choisissez un bord propre et uniforme.", "L’image change. Restez immobile et réessayez.", "Exposition et balance des blancs verrouillées", "La couleur reste automatique ; recalibrez si elle change.", "Rechercher le support", "Support détecté"],
  it: ["Calibra", "Ricerca della base · resta fermo…", "Base stimata e fissata", "Campione della base fissato", "Negativo originale: scegli un bordo arancione pulito, senza immagini né perforazioni.", "Negativo originale: scegli un bordo trasparente non esposto.", "Tocca o trascina sul bordo pulito.", "Campione uniforme. Conferma per applicare.", "Annulla", "Usa campione", "Base non trovata. Mostra un bordo pulito o selezionalo a mano.", "Zona troppo chiara. Evita i fori e riduci esposizione o retroilluminazione.", "Qui ci sono dettagli. Scegli un bordo pulito e uniforme.", "L’immagine cambia. Resta fermo e riprova.", "Esposizione e bilanciamento del bianco bloccati", "Il colore è ancora automatico; ricalibra se cambia.", "Cerca di nuovo la base", "Base rilevata"],
  el: ["Βαθμονόμηση", "Αναζήτηση βάσης · μείνετε ακίνητοι…", "Εκτιμώμενη βάση σταθερή", "Δείγμα βάσης σταθερό", "Αρχικό αρνητικό: επιλέξτε καθαρή πορτοκαλί άκρη χωρίς εικόνα ή οπές.", "Αρχικό αρνητικό: επιλέξτε διαφανή, μη εκτεθειμένη άκρη.", "Αγγίξτε ή σύρετε στην καθαρή άκρη.", "Ομοιόμορφο δείγμα. Επιβεβαιώστε για εφαρμογή.", "Ακύρωση", "Χρήση δείγματος", "Δεν βρέθηκε βάση. Δείξτε καθαρή άκρη ή επιλέξτε χειροκίνητα.", "Πολύ φωτεινή περιοχή. Αποφύγετε οπές, μειώστε έκθεση ή φωτισμό.", "Η περιοχή έχει λεπτομέρειες. Επιλέξτε καθαρή, ομοιόμορφη άκρη.", "Η εικόνα αλλάζει. Μείνετε ακίνητοι και δοκιμάστε ξανά.", "Έκθεση και ισορροπία λευκού κλειδωμένες", "Αυτόματο χρώμα κάμερας· επαναλάβετε αν αλλάξει.", "Νέα αναζήτηση βάσης", "Εντοπισμένη βάση"],
  vi: ["Hiệu chuẩn", "Đang tìm đế phim · giữ yên…", "Đã ước tính và cố định đế phim", "Đã cố định mẫu đế phim", "Âm bản gốc: chọn mép phim màu cam sạch, tránh hình ảnh và lỗ phim.", "Âm bản gốc: chọn mép trong, chưa phơi sáng.", "Chạm hoặc kéo trên mép phim sạch.", "Mẫu đồng đều. Xác nhận để áp dụng.", "Hủy", "Dùng mẫu này", "Chưa tìm được đế phim. Để lộ mép sạch hoặc chọn thủ công.", "Vùng quá sáng. Tránh lỗ phim, giảm phơi sáng hoặc đèn nền.", "Vùng có chi tiết. Chọn mép sạch và đồng đều.", "Hình đang thay đổi. Giữ yên rồi thử lại.", "Đã khóa phơi sáng và cân bằng trắng", "Màu camera vẫn tự động; hiệu chuẩn lại khi màu thay đổi.", "Tìm lại đế phim", "Đế phim đã phát hiện"],
  id: ["Kalibrasi", "Mencari dasar film · tahan stabil…", "Dasar film diperkirakan dan ditahan", "Sampel dasar film ditahan", "Negatif asli: pilih tepi jingga bersih tanpa gambar atau lubang.", "Negatif asli: pilih tepi bening yang belum terpapar.", "Ketuk atau geser pada tepi bersih.", "Sampel seragam. Konfirmasi untuk menerapkan.", "Batal", "Gunakan sampel", "Dasar film tidak ditemukan. Tampilkan tepi bersih atau pilih manual.", "Area terlalu terang. Hindari lubang, kurangi eksposur atau lampu latar.", "Area berisi detail. Pilih tepi bersih dan seragam.", "Gambar berubah. Tahan stabil lalu coba lagi.", "Eksposur dan white balance terkunci", "Warna kamera masih otomatis; kalibrasi ulang jika berubah.", "Cari dasar film lagi", "Dasar film terdeteksi"],
  hi: ["कैलिब्रेट करें", "फिल्म बेस खोज रहे हैं · स्थिर रखें…", "अनुमानित फिल्म बेस स्थिर किया", "फिल्म बेस नमूना स्थिर किया", "मूल नेगेटिव: चित्र और छेद से दूर साफ नारंगी किनारा चुनें।", "मूल नेगेटिव: बिना एक्सपोज़ हुआ साफ पारदर्शी किनारा चुनें।", "साफ किनारे पर टैप या ड्रैग करें।", "नमूना एकसमान है। लागू करने की पुष्टि करें।", "रद्द करें", "यह नमूना उपयोग करें", "विश्वसनीय फिल्म बेस नहीं मिला। साफ किनारा दिखाएँ या स्वयं चुनें।", "क्षेत्र बहुत उजला है। छेद से बचें, एक्सपोज़र या बैकलाइट घटाएँ।", "इस क्षेत्र में चित्र है। साफ एकसमान किनारा चुनें।", "चित्र बदल रहा है। स्थिर रखकर फिर कोशिश करें।", "कैमरा एक्सपोज़र और व्हाइट बैलेंस लॉक हैं", "कैमरे का रंग स्वचालित है; बदलने पर फिर कैलिब्रेट करें।", "फिल्म बेस फिर खोजें", "पता चला फिल्म बेस"],
  ko: ["보정", "필름 베이스 찾는 중 · 움직이지 마세요…", "베이스 추정 및 고정됨", "채취한 베이스 고정됨", "원본 네거티브: 영상과 구멍을 피해 깨끗한 주황색 가장자리를 선택하세요.", "원본 네거티브: 노출되지 않은 투명한 가장자리를 선택하세요.", "깨끗한 가장자리를 탭하거나 드래그하세요.", "균일한 샘플입니다. 확인하면 적용됩니다.", "취소", "이 샘플 사용", "베이스를 찾지 못했습니다. 깨끗한 가장자리를 보이거나 직접 선택하세요.", "너무 밝습니다. 구멍을 피하고 노출이나 조명을 낮추세요.", "무늬가 있는 영역입니다. 깨끗하고 균일한 가장자리를 선택하세요.", "화면이 변하고 있습니다. 고정한 뒤 다시 시도하세요.", "카메라 노출과 화이트 밸런스 잠김", "카메라 색상이 자동입니다. 색이 변하면 다시 보정하세요.", "베이스 다시 찾기", "감지된 필름 베이스"],
  uk: ["Калібрувати", "Шукаємо основу · тримайте нерухомо…", "Основу оцінено й зафіксовано", "Зразок основи зафіксовано", "Оригінальний негатив: виберіть чистий помаранчевий край без зображення й отворів.", "Оригінальний негатив: виберіть прозорий неекспонований край.", "Торкніться чистого краю або перетягніть точку.", "Зразок однорідний. Підтвердьте застосування.", "Скасувати", "Використати зразок", "Основу не знайдено. Покажіть чистий край або виберіть вручну.", "Занадто яскраво. Уникайте отворів, зменште експозицію чи підсвічування.", "Тут є деталі. Виберіть чистий однорідний край.", "Зображення змінюється. Тримайте нерухомо й повторіть.", "Експозицію та баланс білого заблоковано", "Колір камери автоматичний; повторіть калібрування, якщо він зміниться.", "Знайти основу знову", "Виявлена основа"],
  ar: ["معايرة", "جارٍ البحث عن قاعدة الفيلم · ثبّت الكاميرا…", "تم تقدير قاعدة الفيلم وتثبيتها", "تم تثبيت عينة القاعدة", "السالب الأصلي: اختر حافة برتقالية نظيفة بلا صورة أو ثقوب.", "السالب الأصلي: اختر حافة شفافة غير معرّضة للضوء.", "المس أو اسحب على الحافة النظيفة.", "العينة متجانسة. أكّد لتطبيقها.", "إلغاء", "استخدام العينة", "لم نجد قاعدة موثوقة. أظهر حافة نظيفة أو اخترها يدوياً.", "المنطقة شديدة السطوع. تجنب الثقوب وخفّض التعريض أو الإضاءة الخلفية.", "المنطقة تحتوي تفاصيل. اختر حافة نظيفة ومتجانسة.", "الصورة تتغير. ثبّت الكاميرا وحاول مجدداً.", "تم قفل التعريض وتوازن الأبيض", "لون الكاميرا تلقائي؛ أعد المعايرة إذا تغيّر.", "البحث عن القاعدة مجدداً", "قاعدة الفيلم المكتشفة"],
  he: ["כיול", "מחפש בסיס סרט · החזיקו יציב…", "בסיס הסרט הוערך ונקבע", "דגימת הבסיס נקבעה", "הנגטיב המקורי: בחרו שוליים כתומים נקיים ללא תמונה או חורים.", "הנגטיב המקורי: בחרו שוליים שקופים שלא נחשפו.", "געו או גררו על השוליים הנקיים.", "הדגימה אחידה. אשרו להחלה.", "ביטול", "שימוש בדגימה", "לא נמצא בסיס אמין. חשפו שוליים נקיים או בחרו ידנית.", "האזור בהיר מדי. הימנעו מחורים והפחיתו חשיפה או תאורה אחורית.", "באזור יש פרטים. בחרו שוליים נקיים ואחידים.", "התמונה משתנה. החזיקו יציב ונסו שוב.", "החשיפה ואיזון הלבן נעולים", "צבע המצלמה אוטומטי; כיילו שוב אם הוא משתנה.", "חיפוש בסיס מחדש", "בסיס הסרט שזוהה"],
};

const sampleWarnings = {
  en: "This sample contains grain or detail. Choose a smoother film edge, or use this sample if the area is clear film.",
  zh: "此处有颗粒或纹理。建议换更均匀的片边；若确认是无影像片基，也可使用此取样。",
  ja: "粒子や模様があります。より均一な片縁を選ぶか、画像のない片基ならこの取様を使用できます。",
  ru: "В образце есть зерно или детали. Выберите более ровный край или используйте образец, если это чистая основа плёнки.",
  es: "La muestra tiene grano o detalles. Elige un borde más uniforme o úsala si es base sin imagen.",
  fr: "L’échantillon contient du grain ou des détails. Choisissez un bord plus uniforme, ou utilisez-le s’il s’agit du support sans image.",
  it: "Il campione contiene grana o dettagli. Scegli un bordo più uniforme oppure usalo se è base senza immagine.",
  el: "Το δείγμα έχει κόκκο ή λεπτομέρειες. Επιλέξτε πιο ομοιόμορφη άκρη ή χρησιμοποιήστε το αν είναι βάση χωρίς εικόνα.",
  vi: "Mẫu có hạt hoặc chi tiết. Chọn mép đều hơn, hoặc dùng mẫu nếu đây là đế phim không có hình ảnh.",
  id: "Sampel mengandung butiran atau detail. Pilih tepi lebih rata, atau gunakan jika ini dasar film tanpa gambar.",
  hi: "नमूने में दाने या चित्र के अंश हैं। अधिक एकसमान किनारा चुनें, या यदि यह चित्र रहित फिल्म बेस है तो इसका उपयोग करें।",
  ko: "샘플에 입자나 무늬가 있습니다. 더 균일한 가장자리를 선택하거나, 영상이 없는 베이스라면 이 샘플을 사용하세요.",
  uk: "У зразку є зерно або деталі. Виберіть рівніший край або використайте зразок, якщо це основа без зображення.",
  ar: "تحتوي العينة على حبيبات أو تفاصيل. اختر حافة أكثر تجانساً، أو استخدم العينة إن كانت قاعدة فيلم بلا صورة.",
  he: "בדגימה יש גרעיניות או פרטים. בחרו שוליים אחידים יותר, או השתמשו בדגימה אם זהו בסיס ללא תמונה.",
};

export function calibrationLabels(locale) {
  return {
    ...Object.fromEntries(keys.map((key, i) => [key, (translations[locale] || translations.en)[i]])),
    sampleWarningTextured: sampleWarnings[locale] || sampleWarnings.en,
  };
}
